name: Bluelibre_AiHelper (example)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run AI Review
        uses: ./.  # if testing locally in the same repo; replace with owner/repo@version when published
        with:
          github_token: ${{ github.token }}
          google_api_key: ${{ secrets.GOOGLE_API_KEY }}
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}