name: Champ AI Code Review
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Only run on PRs targeting master branch

permissions:
  contents: read
  pull-requests: write

jobs:
  ai_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Run Champ AI Code Review
        uses: AirysDark/BlueLibre
        with:
          github_token: ${{ secrets.GAPI }}
          google_api_key: ${{ secrets.GOOGLE_APII_KEY }}
